apiVersion: v1
kind: ConfigMap
metadata:
  name: oes-audit-client
data:
  providerConfig: |
    application: isdapp
    lifetimeMinutes: 4
    gitops: true
    passScore: 90
    serviceList: 
    - metricScopeVariables: "${namespace_key},${pod_key},${app_name}"
      baselineMetricScope: "isd,.*{{env.STABLE_POD_HASH}}.*,oes"
      canaryMetricScope: "isd,.*{{env.LATEST_POD_HASH}}.*,oes"
      metricTemplateName: "prometheus-health-validator"
      serviceName: oes-audit-client
    - logTemplateName: elklogtemp
      logScopeVariables: "kubernetes.pod_name"
      baselineLogScope: "baseapp-rest-1"
      canaryLogScope: "canaryapp-rest-1"
      serviceName : oes-audit-client
